Add 256 filename support (prefix + name) and add support for space terminated numbers and non-null terminated names (#10)
* Add 256 filename support (prefix + name) and add support for space terminated numbers.

* Format check passes. Add missing file.

* Act on clippy issues found

* fx nit and idiomatic conditional compile

* Clippy is wrong as from_utf8 is not yet stable for const fn usage.

* Move long or deep filenames for tar file creation into a tar file. Normally these aren't needed as the .tar files are used in the source. The tests themselves note what files they depend on.

* Upgrade MSVR as there are dependencies in the tree where SemVer is upgrading them past
the Rust 1.60 compiler. Example from an indirectly dependent crate on Linux:

error: package `rustix v0.38.11` cannot be built because it requires rustc 1.63 or newer, while the currently active rustc version is 1.60.0